import { createClient } from '@supabase/supabase-js';

// These values are provided in the user request.
// In a real-world scenario, they should be in a .env file.
const supabaseUrl = 'https://dmcwmlmwlajjaekepajc.supabase.co';
const supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtY3dtbG13bGFqamFla2VwYWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyNzc0MzIsImV4cCI6MjA3Njg1MzQzMn0.NKEY09WbUDTh-G9GXCsVnKZdfpU5rGdTUr-uhwVQ4ss';

if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error('Supabase URL and Anon Key must be provided.');
}

export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * Checks if the 'projects' table exists, and if not, calls an RPC function 
 * to create the table, storage bucket, and necessary policies.
 * This ensures the application can self-initialize on first run.
 */
export const ensureProjectResourcesExist = async () => {
  // 1. Check if the table exists by trying a lightweight query.
  const { error: checkError } = await supabase
    .from('projects')
    .select('id', { count: 'exact', head: true });

  // Postgres error code for "undefined_table" is 42P01.
  // If we don't get this specific error, we assume the table exists or some other issue occurred.
  if (!checkError || (checkError && checkError.code !== '42P01')) {
    console.log('Project resources are already set up.');
    return;
  }

  // 2. If the table doesn't exist, call the RPC function to create resources.
  console.log("Projects table not found. Attempting to create resources via RPC...");
  const { error: rpcError } = await supabase.rpc('setup_project_resources');

  if (rpcError) {
    console.error('RPC call to setup_project_resources failed:', rpcError);
    throw new Error(
      'Failed to automatically set up database resources.\n' +
      'Please go to your Supabase dashboard, open the SQL Editor, and run the setup script provided in the comments of `services/supabase.ts`.\n\n' +
      'Error details: ' + rpcError.message
    );
  }

  console.log('Successfully created project resources.');
};

/*
-- =================================================================================================
-- IMPORTANT: ONE-TIME SETUP SCRIPT FOR SUPABASE
-- =================================================================================================
-- To enable the automatic setup feature, please run this entire SQL script ONCE 
-- in your Supabase project's SQL Editor.
-- Go to: Database -> SQL Editor -> New query
-- =================================================================================================

CREATE OR REPLACE FUNCTION setup_project_resources()
RETURNS VOID AS $$
BEGIN
  -- Create projects table if it doesn't exist
  IF NOT EXISTS (
    SELECT FROM pg_catalog.pg_tables
    WHERE schemaname = 'public' AND tablename = 'projects'
  ) THEN
    CREATE TABLE public.projects (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
      title TEXT NOT NULL,
      description TEXT NOT NULL,
      tags TEXT[] NOT NULL,
      media_urls TEXT[] NOT NULL,
      storage_provider TEXT NOT NULL,
      thumbnail_url TEXT
    );
    -- Enable Row Level Security (RLS)
    ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
    -- Create RLS policies
    CREATE POLICY "Allow public read access" ON public.projects FOR SELECT USING (true);
    CREATE POLICY "Allow insert for authenticated users" ON public.projects FOR INSERT TO authenticated WITH CHECK (true);
    CREATE POLICY "Allow update for authenticated users" ON public.projects FOR UPDATE TO authenticated USING (true);
    CREATE POLICY "Allow delete for authenticated users" ON public.projects FOR DELETE TO authenticated USING (true);
  END IF;

  -- Create storage bucket if it doesn't exist
  IF NOT EXISTS (SELECT 1 FROM storage.buckets WHERE id = 'projects-media') THEN
    INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
    VALUES ('projects-media', 'projects-media', true, 52428800, ARRAY['image/*', 'video/*']); -- 50MB limit
  END IF;

  -- Create storage policies if they don't exist
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'Public read access for projects-media') THEN
    CREATE POLICY "Public read access for projects-media" ON storage.objects FOR SELECT USING (bucket_id = 'projects-media');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'Allow uploads for authenticated users') THEN
    CREATE POLICY "Allow uploads for authenticated users" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'projects-media');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'Allow updates for authenticated users') THEN
    CREATE POLICY "Allow updates for authenticated users" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'projects-media');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policy WHERE polname = 'Allow deletes for authenticated users') THEN
    CREATE POLICY "Allow deletes for authenticated users" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'projects-media');
  END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
*/
